"""
WanderHUB Backend — SQLite Connection Manager
"""

import sqlite3
import shutil
from contextlib import contextmanager
from pathlib import Path

from config import DB_PATH, SEED_DB_PATH

SCHEMA_EXTENSIONS = """
-- Users table for authentication
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    preferences_json TEXT,
    budget_default INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Itineraries generated by AI
CREATE TABLE IF NOT EXISTS itineraries (
    id INTEGER PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    title TEXT NOT NULL,
    mood_code TEXT,
    district_preference TEXT,
    budget_min INTEGER,
    budget_max INTEGER,
    time_start TEXT,
    time_end TEXT,
    transport_mode TEXT,
    total_cost_estimated INTEGER,
    total_duration_min INTEGER,
    status TEXT DEFAULT 'active',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Itinerary stops (provider waypoints)
CREATE TABLE IF NOT EXISTS itinerary_stops (
    id INTEGER PRIMARY KEY,
    itinerary_id INTEGER NOT NULL REFERENCES itineraries(id) ON DELETE CASCADE,
    provider_id INTEGER NOT NULL REFERENCES providers(id),
    step_order INTEGER NOT NULL,
    arrival_time TEXT,
    duration_min INTEGER,
    cost_estimated INTEGER,
    reason TEXT,
    status TEXT DEFAULT 'active'
);

-- Contact form submissions
CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Itinerary feedback for AI learning
CREATE TABLE IF NOT EXISTS itinerary_feedback (
    id INTEGER PRIMARY KEY,
    itinerary_id INTEGER REFERENCES itineraries(id),
    user_id INTEGER REFERENCES users(id),
    rating INTEGER CHECK(rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Recommendation sessions store each customer intent before AI scoring.
CREATE TABLE IF NOT EXISTS recommendation_sessions (
    id INTEGER PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    itinerary_id INTEGER REFERENCES itineraries(id),
    mood_input TEXT,
    district TEXT,
    budget_max INTEGER,
    time_start TEXT,
    time_end TEXT,
    transport_mode TEXT,
    parsed_context_json TEXT,
    rules_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- User interactions let the recommender learn from hover/click/choose/dislike behavior.
CREATE TABLE IF NOT EXISTS user_interactions (
    id INTEGER PRIMARY KEY,
    session_id INTEGER REFERENCES recommendation_sessions(id) ON DELETE SET NULL,
    user_id INTEGER REFERENCES users(id),
    itinerary_id INTEGER REFERENCES itineraries(id) ON DELETE SET NULL,
    provider_id INTEGER REFERENCES providers(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (
        event_type IN ('view', 'hover', 'click', 'choose', 'save', 'dislike', 'reroute')
    ),
    weight REAL NOT NULL DEFAULT 1,
    metadata_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_interactions_user_provider
    ON user_interactions(user_id, provider_id);
CREATE INDEX IF NOT EXISTS idx_user_interactions_session
    ON user_interactions(session_id);
CREATE INDEX IF NOT EXISTS idx_user_interactions_event
    ON user_interactions(event_type);

-- Keep an audit trail of which recommendations were shown and why.
CREATE TABLE IF NOT EXISTS recommendation_logs (
    id INTEGER PRIMARY KEY,
    session_id INTEGER REFERENCES recommendation_sessions(id) ON DELETE CASCADE,
    itinerary_id INTEGER REFERENCES itineraries(id) ON DELETE SET NULL,
    provider_id INTEGER REFERENCES providers(id) ON DELETE CASCADE,
    rank_position INTEGER NOT NULL,
    score REAL,
    reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_recommendation_logs_session
    ON recommendation_logs(session_id);
"""


def _make_connection(db_path: Path | str) -> sqlite3.Connection:
    """Create a new SQLite connection with row_factory and WAL mode."""
    if Path(db_path) != SEED_DB_PATH and not Path(db_path).exists():
        shutil.copyfile(SEED_DB_PATH, db_path)
    conn = sqlite3.connect(str(db_path), check_same_thread=False)
    conn.row_factory = sqlite3.Row
    try:
        conn.execute("PRAGMA journal_mode=WAL")
    except sqlite3.OperationalError:
        pass
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def init_db() -> None:
    """Apply schema extensions (idempotent — CREATE IF NOT EXISTS)."""
    with _make_connection(DB_PATH) as conn:
        conn.executescript(SCHEMA_EXTENSIONS)
        conn.commit()
    print(f"[DB] Schema extensions applied to {DB_PATH}")


@contextmanager
def get_db():
    """Yield a SQLite connection, closing it when done."""
    conn = _make_connection(DB_PATH)
    try:
        yield conn
    finally:
        conn.close()


def get_db_dependency():
    """FastAPI Depends() generator for request-scoped connections."""
    conn = _make_connection(DB_PATH)
    try:
        yield conn
    finally:
        conn.close()
